#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog

#Get BIOS OEM revision
#bios_oem_check QA5TRT01
bios_rev_check JVWLR124
bios_sn_check 

#Check Memory size
memory_check 3805 3806
#check BIOS time before ex.2020
#hwclock_check 2020

#Get MAC for log
lan_mac_check eno1 00:13:95
lan_mac_check enp1s0 00:13:95

#lan_ping_check 192.168.1.1
#lan_ping_check 192.168.4.1

#Update time from NTP server
#time_ntp_set

#check BIOS time from internet
hwclock_check_live

#check USB device
usb_dev_count "Bus 001" 4
usb_dev_count "Bus 002" 3

#ssd speed check 
ssd_speed_check /dev/sdb 200 


#RS232 loopback test
serial_loop_test /dev/ttyS0

#input spec of cpu temp low high limit to script ex.20 70
cpu_temp_check +20 +45

#Show ALL TEST PASS to log
pass_green_dialog

