#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./ss_func

#Update time from NTP server
time_ntp_set

#Get SN for Log
sn_get_dialog

#Get AIC info for Log
aic_info_get
aic_fw_check "AIC-1.00"
aic_logo_check None
aic_rtc_check
aic_poe_check 1
aic_poe_check 2
aic_poe_check 3
aic_poe_check 4
aic_com_check 1 RS232
aic_com_check 2 RS232
aic_atx_check ATX
aic_usb_check 1
aic_usb_check 2
aic_usb_check 3
aic_usb_check 4
aic_fan_cfg_check 1
aic_fan_rpm_check 1
aic_gpio_check FF00

#Check BIOS version
bios_version_check 1.10

#Get MAC for log
lan_mac_check eno1 80:7b:85
lan_mac_check enp1s0 80:7b:85

#ping test
#lan_ping_check 192.168.1.1
lan_carrier_check eno1
lan_carrier_check enp1s0

lan_ip_check eno1
lan_ip_check enp1s0

#check USB device
usb_dev_count "Bus 001" 7
usb_dev_count "Bus 002" 2

#RS232 loopback test
serial_loop_test /dev/ttyS0

#Audio loopbakc test
mic_loopback_test 80

#input spec of cpu temp low high limit to script ex.20 70
cpu_temp_check +30 +40

#check BIOS time from internet
hwclock_check_live

#system info log
system_info_log

#Show ALL TEST PASS to log
pass_green_dialog

