#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog


#Get MAC for log
lan_mac_check enp1s0 80:7b:85

#check BIOS time from internet
hwclock_check 2021

#BI for $3 x 10m
bi_stress_com +20 +90 130

#RS232 loopback test
#serial_loop_test /dev/ttyS0

#input spec of cpu temp low high limit to script ex.20 70
#cpu_temp_check +30 +95

#Show ALL TEST PASS to log
pass_green_dialog

