#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog
#sn_get_dialog_loop

#Get BIOS revision
bios_rev_dmidecode_get

#Display check
display_check DP1
display_check DP2

#memory check 
memory_check 7868 7908

#Get MAC for log
lan_mac_check enp1s0 80:7b:85
lan_mac_check enp4s0 00:13:95
#lan_test
lan_carrier_check enp1s0
lan_carrier_check enp4s0
lan_ip_check enp1s0
lan_ip_check enp4s0

#Update time from NTP server
#time_ntp_set

#check BIOS time from internet
hwclock_check_live

#check USB device
usb_dev_count "Bus 002" 7
usb_dev_count "Bus 003" 2

#ssd speed check 
ssd_speed_check /dev/sdc1 200 
#usb30 and mSATA speed check 
ssd_speed_check /dev/sda 300 


#Audio MIC test
alsabat_loopback_test

#RS232 loopback test
#serial_loop_test /dev/ttyS0


#input spec of cpu temp low high limit to script ex.20 70
cpu_temp_check +20 +50

#Show ALL TEST PASS to log
pass_green_dialog

