#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_nodate_dialog

#Get BIOS OEM revision
bios_oem_check QC31U912

#Set BIOS time
#hwclock_write 2020-06-14

#check BIOS time ex.2020
hwclock_check 2020

#Get MAC for log
lan_mac_check enp1s0 80:7b:85
lan_mac_check enp4s0 00:13:95

#lan1_ping_test
lan_down enp4s0
lan_up enp1s0
lan_ping_check 192.168.0.1
#lan2_ping_test
lan_down enp1s0
lan_up enp4s0
lan_ping_check 192.168.0.1

#check USB device
usb_dev_count "Bus 002" 8
usb_dev_count "Bus 003" 2

#usb_id_check "8564:1000"

ssd_speed_check /dev/sda 500  
ssd_speed_check /dev/sdc 200 

#IDIO loopback test
idio_loopback_test

#Audio MIC sum test
mic_test 40

#RS232 loopback test
serial_loop_test /dev/ttyS0
serial_loop_test /dev/ttyS1
serial_loop_test /dev/ttyS2
serial_loop_test /dev/ttyS3


#input spec of $1 BI to script ex.disk/nodisk $2 is BI time
#bi_cli_auto noserial 1

#input spec of cpu temp low high limit to script ex.20 70
#cpu_temp_check +30 +40


#Show ALL TEST PASS to log
pass_green_dialog

