#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_nodate_dialog

#Set BIOS time
hwclock_write 2020-06-14
#check BIOS time ex.2020
hwclock_check 2020

#lan_mac_progrem
mac_get_dialog
mac_scan_check
#mac_nvm_write /NIC=1
mac_addr_write /NIC=1

#Show ALL TEST PASS to log
pass_green_dialog

