#!/bin/bash
# utilitymenu.sh - A sample shell script to display menus on screen
# Store menu options selected by the user
#set -xv


REV=$(cat /home/production/hw_test/revision | head -1 | awk '{print $1}')
TEST_LOC=/home/production/hw_test
PN_TMP=/tmp/pn.tmp
MODEL=$0

# if temp files found, delete em
rm $PN_TMP

dialog --title "$MODEL Test" \
--inputbox "Cancel=Back to MAIN-MENU \nPlease Scan the SN of Label:" \
10 40 2> $PN_TMP
PN=$(cat $PN_TMP | cut -c 1-6) 

#:: 17.V3CE6         (20070-000611) 2019/5/31 Add    18.V3C           (20070-000560) 2019/5/31 Add 
#:: 19.V3CDP         (20070-000633) 2019/5/31 Add    20.V2CL6-6600    (20040-000005) 2019/10/18 Add
#:: 27.V3CEL7-7200   (20040-000014) 2019/10/18 Add   28.V2C7-7200     (20070-000691) 2019/11/5 Add

case $PN in
	000026)
		clear
		cd $TEST_LOC; sudo sh V3C6RN
		exit 0
		;;
	000027)
		clear
		cd $TEST_LOC; sudo sh V3C4RN
		exit 0
		;;	
	000560)
		clear
		cd $TEST_LOC; sudo sh V3C6
		exit 0
		;;		
	000561)
		clear
		cd $TEST_LOC; sudo sh V3CD6
		exit 0
		;;	
	000633)
		clear
		cd $TEST_LOC; sudo sh V3CDP6
		exit 0
		;;
	*)	
		clear
		echo "\e[1;5;33;47m The PN not find for test! \e[0m"
		sleep 5
		echo "cd $TEST_LOC; sudo sh run_main.sh" > $TEST_LOC/t.sh
                sudo sh $TEST_LOC/t.sh
                exit 1
		;;	

esac



