#!/bin/bash
# utilitymenu.sh - A sample shell script to display menus on screen
# Store menu options selected by the user
#set -xv
INPUT=/tmp/menu
OUTPUT=/tmp/output
REV=$(cat /home/production/hw_test/revision | head -1 | awk '{print $1}')
TEST_LOC=/home/production/hw_test
N1=QA5TRT01-BIOS-UPDATE
N2=Q7XX-T1-VTRON
N3=Q718PAS-T2
N4=Q718-T2
N5=Q715-T2
N6=TRITIUM-Q715QA5-T2
N7=Q715-VT2-1

# if temp files found, delete em
rm $OUTPUT
rm $INPUT





### display main menu ###<high><width><menu_hight>
dialog --clear --title "[ PCBA Test- MENU ]" \
--menu "Cancel=Back to MAIN-MENU \nUse 1-9 choose test item \nBuild by EFCO SamLee REV:$REV" 30 50 15 \
1 "$N1" \
2 "$N2" \
3 "$N3" \
4 "$N4" \
5 "$N5" \
6 "$N6" \
7 "$N7" \
2>$INPUT
#2>"${INPUT}"

menuitem=$(cat $INPUT)
#response=$?
# make decsion 

case $(cat $INPUT) in
	1)
		clear
		echo "cd $TEST_LOC; sudo sh $N1" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 0
		;;
	2) 
		echo "2"
		clear
		echo "cd $TEST_LOC; sudo sh $N2" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 2
		;;
	3) 
		echo "3"
		clear
		echo "cd $TEST_LOC; sudo sh $N3" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 3
		;;
	4) 
		echo "4"
		clear
		echo "cd $TEST_LOC; sudo sh $N4" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 4
		;;
	5) 
		echo "5"
		clear
		echo "cd $TEST_LOC; sudo sh $N5" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 5
		;;
	6) 
		echo "6"
		clear
		echo "cd $TEST_LOC; sudo sh $N6" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 6
		;;
	7) 
		echo "7"
		clear
		echo "cd $TEST_LOC; sudo sh $N7" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 7
		;;
	*)
		clear
                echo "cd $TEST_LOC; sudo sh run_main.sh" > $TEST_LOC/t.sh
                sudo sh $TEST_LOC/t.sh
                exit 1
                ;;

esac



