#!/bin/bash
# utilitymenu.sh - A sample shell script to display menus on screen
# Store menu options selected by the user
set -xv
INPUT=/tmp/menu
OUTPUT=/tmp/output
REV=$(cat /home/production/hw_test/revision | head -1 | awk '{print $1}')
TEST_LOC=/home/production/hw_test
N1=WIN10IOT-2016-LSTB-ENG-EPKEA-AIM
N2=WIN10IOT-2019-LSTC-ENG-EPKEA-AIMH
N3=WIN10IOT-2019-LSTC-ENG-EPKEA-U7130
N4=WIN10IOT-2016-LSTB-CN-EPKEA-SA50
N5=55015-000011-WIN10IOT-2019-LSTC-CHT-EPKEA-AIMH



# if temp files found, delete em
rm $OUTPUT
rm $INPUT





### display main menu ###<high><width><menu_hight>
dialog --clear --title "[ OS_CLONE - MENU ]" \
--menu "Cancel=Back to MAIN-MENU \nUse 1-9 choose test item \nBuild by EFCO SamLee REV:$REV" 30 70 15 \
1 "$N1" \
2 "$N2" \
3 "$N3" \
4 "$N4" \
5 "$N5" \
c "DISK_SPACE&IMAGE_CHECK" \
2>$INPUT
#2>"${INPUT}"

menuitem=$(cat $INPUT)
#response=$?
# make decsion 

case $(cat $INPUT) in
	1)
		echo "1"
		clear
		echo "cd $TEST_LOC; sudo sh $N1" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 1
		;;
	2) 
		echo "2"
		clear
		echo "cd $TEST_LOC; sudo sh $N2" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 2
		;;
	3) 
		echo "3"
		clear
		echo "cd $TEST_LOC; sudo sh $N3" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 3
		;;
	4) 
		echo "4"
		clear
		echo "cd $TEST_LOC; sudo sh $N4" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 4
		;;
	5) 
		echo "5"
		clear
		echo "cd $TEST_LOC; sudo sh $N5" > $TEST_LOC/t.sh
		sudo sh $TEST_LOC/t.sh
		exit 5
		;;
	c)
		clear
		SPACE=$(df | grep /dev/sd)
		IMAGE=$(ls /home/partimag/)
		dialog --title "[DISK SPACE CHECK]" --msgbox "$SPACE $IMAGE" 10 50
		sudo sh $TEST_LOC/t.sh
		exit 0
		;;
#	r)
#		clear
#		dialog --title "[FREE DISK SPACE]" --yesno "Are you sure to delete OS IMAGE?" 10 50
#		response=$?
#		case $response in 
#			0)
#				sudo rm -r /home/partimag/
#				sudo sh $TEST_LOC/t.sh
#				exit 0 ;;
#			1)
#				
#				sudo sh $TEST_LOC/t.sh
#				exit 1 ;;
#		esac
#		;;
	*)
		clear
                echo "cd $TEST_LOC; sudo sh run_main.sh" > $TEST_LOC/t.sh
                sudo sh $TEST_LOC/t.sh
                exit 1
                ;;

esac



