#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./ss_func
#. ./u7_func
#. ./bi_func
#lan_mac_check enp2s0 00:13:95

#countdown $((2*60*60))
#stopwatch 10
#onedrive_to_local

#Get SN for Log
#sn_get_dialog
#bios_rev_check
#at_check /dev/ttyUSB2 'at\r\n' OK
#at_check /dev/ttyUSB2 'at+ciccid\r\n' ICCID
#lan_down enp4s0
#lan_up enp1s0
#lan_ping_check 192.168.0.1
#lan_down enp1s0
#lan_up enp4s0
#lan_ping_check 192.168.0.1

#idio_loopback_test

#serial_loop_test /dev/ttyS0
#serial_loop_test /dev/ttyS2
#serial_loop_test /dev/ttyS1
#mac_get_dialog
#mac_scan_check
#mac_nvm_write /NIC=1
##mac_addr_write /NIC=1
#bios_oem_update
#bios_oem_check
#time_ntp_set
#mic_test 40
alsabat_loopback_test
#mic_loopback_test 50
#serial_loop_test_menu /dev/ttyS0 1
#check BIOS time before BI ex.2020
#hwclock_check 2020

#check USB device

#RS232 loopback test
#LAN test
#os_image_mount
#os_image_sync 123
#bi check
#burnintest_script
#bi_log_check
#bi_stress +20 +95 10
#input spec of $1 BI to script ex.disk/nodisk $2 is BI time
#bi_cli_auto noserial 1

#input spec of cpu temp low high limit to script ex.20 70

#usb30_speed_check

#copy bi log to final log
#usb_log_sync
#Show ALL TEST PASS to log
#pass_green_dialog

