#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog
mac_addr_write /NIC=1
#bios_oem_update
#bios_oem_check
#time_ntp_set
#mic_test 40
#check BIOS time before BI ex.2020
#hwclock_check 2020

#check USB device

#RS232 loopback test
#LAN test

#bi check
#burnintest_script
#bi_log_check

#input spec of $1 BI to script ex.disk/nodisk $2 is BI time
#bi_cli_auto noserial 1

#input spec of cpu temp low high limit to script ex.20 70

#copy bi log to final log

#Show ALL TEST PASS to log
pass_green_dialog

