#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog

#Get BIOS OEM revision
#bios_oem_check QC31U912

#check BIOS time before ex.2020
#hwclock_check 2020

#Get MAC for log
lan_mac_check enp1s0 80:7b:85
lan_mac_check enp4s0 00:13:95
#lan1_ping_test
#lan_down enp4s0
#lan_up enp1s0
lan_ping_check 192.168.1.1
#lan2_ping_test
#lan_down enp1s0
#lan_up enp4s0
lan_ping_check 192.168.4.1

#Update time from NTP server
#time_ntp_set

#check BIOS time from internet
hwclock_check_live

#check USB device
usb_dev_count "Bus 002" 7
usb_dev_count "Bus 003" 2

#usb30 speed check 
ssd_speed_check sdb1 90 

#DIO loopback test
#dio_loopback_test

#Audio MIC sum test
#mic_test 30

#RS232 loopback test
serial_loop_test /dev/ttyS0

#input spec of cpu temp low high limit to script ex.20 70
cpu_temp_check +30 +40

#Show ALL TEST PASS to log
pass_green_dialog

