#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog

#Get MAC for log
lan_mac_check enp1s0 80:7b:85
lan_mac_check enp4s0 00:13:95
#lan_mac_nocheck

#check BIOS time before ex.2020
hwclock_check 2020

#Update time from NTP server
time_ntp_set

#check BIOS time from internet
hwclock_check_live

#check USB device
usb_dev_count "Bus 002" 7
usb_dev_count "Bus 003" 2

#usb_id_check "8564:1000"
ssd_speed_check /dev/sdb 90 USB30

#DIO loopback test
dio_loopback_test

#Audio MIC sum test
mic_test 30

#RS232 and LAN loopback test by PASSMARK
burnintest_script

#bi check
bi_log_check

#input spec of $1 BI to script ex.disk/nodisk $2 is BI time
#bi_cli_auto noserial 1

#input spec of cpu temp low high limit to script ex.20 70
cpu_temp_check +30 +40

#copy bi log to final log
bi_log_copy

#Show ALL TEST PASS to log
pass_green_dialog

