#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog_loop

#Get BIOS OEM revision
bios_oem_update


#Show ALL TEST PASS to log
pass_green_dialog

