#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Get SN for Log
sn_get_dialog_loop

#sshfs mount
#os_image_sync $0

#OS clone
os_clone $0

#Show ALL TEST PASS to log
pass_green_dialog

