#!/bin/bash
# Script for system function test by EFCO Sam

#For Debug
#set -xv

#---Start Function---
. ./u7_func

#Update time from NTP server
#time_zone_set Europe/Berlin
time_zone_set Asia/Taipei
time_ntp_set

#Get SN for Log
sn_get_dialog_loop

#Get BIOS OEM revision
#bios_oem_check QA5TRT01
bios_oem_check SA50MK01
#bios_rev_check SA50MK01
bios_sn_check

#sshfs mount
#os_image_sync $0

#OS clone
os_clone $0

#Show ALL TEST PASS to log
pass_green_dialog

